---
# file: create-user.yml

- name: Install web server
  hosts: webservers
  become: yes

  pre_tasks:
    - file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ deploy_user }}"
        group: "{{ deploy_group }}"
        mode: 0755

  roles:
    - ansible-role-nginx
    - ansible-role-certbot
