---
# file: create-user.yml

- name: Install web server
  hosts: webservers
  become: yes

  pre_tasks:
    - file:
        path: "{{ app_directory }}"
        state: directory
        mode: 0755

  roles:
    - ansible-role-nginx
